id: I4DA6B4BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:49:52+00:00'
last_modified: '2022-06-08T06:22:15.419780+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181152
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་གཏེར་མའི་སྒྲུབ་མཆོད་ལས། ཞི་ཁྲོའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    43FF:
      image_group_id: I1KG16306
      title: ''
      total_pages: 40
      order: 1
      base_file: 43FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
