id: P006718
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:19:00.646035
source_metadata:
  id: bdr:W1PD181152
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་གཏེར་མའི་སྒྲུབ་མཆོད་ལས། ཞི་ཁྲོའི་སྐོར།
  author: ''
  volumes:
    10ba013dab0b4c449d414e10ff237273:
      image_group_id: I1KG16306
      title: ''
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
