id: P006718
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181152
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་གཏེར་མའི་སྒྲུབ་མཆོད་ལས། ཞི་ཁྲོའི་སྐོར།
  author: ''
  volumes:
    10ba013dab0b4c449d414e10ff237273:
      image_group_id: I1KG16306
      title: ''
      volume_number: 1
      total_pages: 40
